permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 郭建珠
  email: guojianzhu1994@foxmail.com
  link: http://guojianzhu.com
  github: http://github.com/cleardusk

# 站点信息
title: 郭建珠的博客 
description: 郭建珠的博客
url: http://guojianzhu.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
#avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
avatar: /assets/pics/me.png
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico
favicon: /assets/pics/me.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: cleardusk
